[workspace]
members = [
    #"core",
    #"chain/ethereum",
    #"graphql",
    #"mock",
    #"node",
    #"runtime/wasm",
    #"runtime/derive",
    #"runtime/test",
    #"server/http",
    #"server/json-rpc",
    #"server/index-node",
    #"server/metrics",
    #"store/postgres",
    #"store/test-store",
    "graph",
    #"tests",
]
