[package]
name = "graph-store-postgres"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = "0.1.50"
blake3 = "1.3"
derive_more = { version = "0.99.17" }
diesel = { workspace = true }
# # We use diesel-dynamic-schema straight from git as the project has not
# # made a release as a crate yet
diesel-dynamic-schema = "0.2.0"
diesel-derive-enum = { workspace = true }
# diesel_enum_derive = "1.0.1"
diesel_migrations = "2.0.0"
diesel_derives = { workspace = true }
fallible-iterator = "0.2.0"
graph = { path = "../../graph" }
graph-graphql = { path = "../../graphql" }
Inflector = "0.11.3"
lazy_static = "1.1"
lru_time_cache = "0.11"
maybe-owned = "0.3.4"
postgres = "0.19.1"
openssl = "0.10.45"
postgres-openssl = "0.5.0"
rand = "0.8.4"
serde = "1.0"
uuid = { version = "1.1.2", features = ["v4"] }
stable-hash_legacy = { version = "0.3.3", package = "stable-hash" }
anyhow = "1.0.68"
git-testament = "0.2.0"
itertools = "0.10.5"
pin-utils = "0.1"
hex = "0.4.3"

[dev-dependencies]
futures = "0.3"
clap = "3.2.23"
graphql-parser = "0.4.0"
test-store = { path = "../test-store" }
hex-literal = "0.3"
graph-chain-ethereum = { path = "../../chain/ethereum" }
graph-mock = { path = "../../mock" }
