name: Publish multiarch images on ghcr.io
on:
  push:
    branches:    
      - master
      - development

env:
  REGISTRY: alfredcapital
  IMAGE_NAME: graph-node

jobs:
  publish:
    strategy:
      matrix:
        runs-on: [ ubuntu-latest, buildjet-4vcpu-ubuntu-2204-arm ]
    runs-on: ${{matrix.runs-on}}
    name: Build and push graph-node multiarch images
    permissions:
      contents: 'read'
      packages: 'write'
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Derive image name
      id: image
      run: |
        IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
        echo "NAME=$IMAGE" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push multiarch image
      uses: docker/build-push-action@v4
      with:
        push: true
        context: .
        file: ./docker/Dockerfile
        tags: "${{ steps.image.outputs.NAME }}"
        cache-from: type=gha
        cache-to: type=gha,mode=max
        # platforms: linux/amd64,linux/arm64
        # platforms: linux/amd64
